btn = QPushButton()
btn.setText("")
btn.setObjectName("btn")
btn.setFixedSize(90,90)
btn.setIcon(QIcon("image/create"))
btn.setIconSize(QSize(60,60))
btn.setCursor(QCursor(Qt.PointingHandCursor))
btn.setAlignment(Qt.AlignCenter)
