gs = QPushButton()
gs.setText("")
gs.setObjectName("bg")
gs.setFixedSize(35,35)
gs.setIcon(QIcon("image/settings"))
gs.setIconSize(QSize(25,25))
gs.setCursor(QCursor(Qt.PointingHandCursor))
gs.setAlignment(Qt.AlignCenter)
